[package]
name = "test-data-generator"
version = "0.1.0"
authors = ["John 9e9 <jn9e9e9@gmail.com>"]
edition = "2018"

[dependencies]
parsec-interface = "0.23.0"
psa-crypto = "0.7.0"
base64 = "0.13.0"
serde = "1.0.123"
serde_json = "1.0"
uuid = "0.8.2"
zeroize = "1.2.0"

